DROP DATABASE IF EXISTS los_mismos;

CREATE DATABASE los_mismos;
USE los_mismos;

-- TABLA USUARIOS
CREATE TABLE USUARIOS (
    idUsuario SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(59) NOT NULL,
    Email VARCHAR(80) NOT NULL,
    Tipo BIT(1) NOT NULL DEFAULT b'1'
);

-- TABLA TEMAS
CREATE TABLE TEMAS (
    idTema TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL
);

-- TABLA GRUPO
CREATE TABLE GRUPO (
    idGrupo TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL
);

-- TABLA SUGERENCIAS
CREATE TABLE SUGERENCIAS (
    idSugerencia INT AUTO_INCREMENT PRIMARY KEY,
    Texto VARCHAR(250) NOT NULL,
    Fecha DATETIME NOT NULL DEFAULT NOW(),
    idTema TINYINT UNSIGNED NOT NULL,
    idGrupo TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY (idTema) REFERENCES TEMAS(idTema),
    FOREIGN KEY (idGrupo) REFERENCES GRUPO(idGrupo)
);

-- TABLA CONTACTO
CREATE TABLE CONTACTO (
    idContacto SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nombre CHAR(20) NOT NULL
);

-- TABLA INTERMEDIA SUGERENCIA_CONTACTO
CREATE TABLE SUGERENCIA_CONTACTO (
    idSugerencia INT,
    idContacto SMALLINT UNSIGNED,
    PRIMARY KEY (idSugerencia, idContacto),
    FOREIGN KEY (idSugerencia) REFERENCES SUGERENCIAS(idSugerencia),
    FOREIGN KEY (idContacto) REFERENCES CONTACTO(idContacto)
);

-- INSERTAR GRUPOS
INSERT INTO GRUPO (Nombre) VALUES 
('Asociacion'),
('Comparsa');

-- INSERTAR TEMAS
INSERT INTO TEMAS (Nombre) VALUES 
('Fiesta'),
('Baile'),
('Musica'),
('Normas'),
('Convivencias'),
('Traje');

-- INSERTAR CONTACTO
INSERT INTO CONTACTO (Nombre) VALUES 
('Youtube'),
('Amigo'),
('Revista'),
('Internet');
