DROP DATABASE IF EXISTS los_mismos;

CREATE DATABASE los_mismos;
USE los_mismos;

-- TABLA USUARIOS
CREATE TABLE USUARIOS (
    idUsuario SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(59) NOT NULL,
    Email VARCHAR(80) NOT NULL,
    Tipo TINYINT(1) NOT NULL DEFAULT 1
);

-- TABLA TEMAS
CREATE TABLE TEMAS (
    idTema TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL
);

-- TABLA GRUPOS
CREATE TABLE GRUPOS (
    idGrupo TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL
);

-- TABLA SUGERENCIAS
CREATE TABLE SUGERENCIAS (
    idSugerencia INT AUTO_INCREMENT PRIMARY KEY,
    Texto VARCHAR(250) NOT NULL,
    Fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    idTema TINYINT UNSIGNED NOT NULL,
    idGrupo TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY (idTema) REFERENCES TEMAS(idTema),
    FOREIGN KEY (idGrupo) REFERENCES GRUPOS(idGrupo)
);

-- TABLA CONTACTOS
CREATE TABLE CONTACTOS (
    idContacto SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(20) NOT NULL
);

-- TABLA INTERMEDIA SUGERENCIA_CONTACTO
CREATE TABLE SUGERENCIA_CONTACTO (
    idSugerencia INT,
    idContacto SMALLINT UNSIGNED,
    PRIMARY KEY (idSugerencia, idContacto),
    FOREIGN KEY (idSugerencia) REFERENCES SUGERENCIAS(idSugerencia),
    FOREIGN KEY (idContacto) REFERENCES CONTACTOS(idContacto)
);

-- INSERTAR GRUPOS
INSERT INTO GRUPOS (Nombre) VALUES 
('Asociacion'),
('Comparsa');

-- INSERTAR TEMAS
INSERT INTO TEMAS (Nombre) VALUES 
('Fiesta'),
('Baile'),
('Musica'),
('Normas'),
('Convivencias'),
('Traje');

-- INSERTAR CONTACTOS
INSERT INTO CONTACTOS (Nombre) VALUES 
('Youtube'),
('Amigo'),
('Revista'),
('Internet');
